x-common-variables: &common-env
  KAFKA_S3_ACCESS_KEY: admin
  KAFKA_S3_SECRET_KEY: password
  KAFKA_HEAP_OPTS: -Xms1g -Xmx4g -XX:MetaspaceSize=96m -XX:MaxDirectMemorySize=1G
  # Replace CLUSTER_ID with a unique base64 UUID using "bin/kafka-storage.sh random-uuid"
  CLUSTER_ID: 5XF4fHIOTfSIqkmje2KFlg

services:
  producer:
    build: ./kafka-producer
    container_name: kafka-producer
    depends_on:
      automq:
        condition: service_healthy
      schema-registry:
        condition: service_started
    environment:
      BOOTSTRAP: "automq:9092"
      SCHEMA_REGISTRY: "http://schema-registry:8081"
      TOPIC: "user_events"
      FLUSH_EVERY: "500"
      SLEEP_MIN_SEC: "0.005"
      SLEEP_MAX_SEC: "0.02"
      AUTO_REGISTER_SCHEMAS: True
      LOG_LEVEL: "INFO"
    networks:
      - iceberg_net
    restart: unless-stopped
  rest:
    image: docker.arvancloud.ir/apache/iceberg-rest-fixture
    container_name: iceberg-rest
    networks:
      iceberg_net:
    ports:
      - 8181:8181
    environment:
      - AWS_ACCESS_KEY_ID=admin
      - AWS_SECRET_ACCESS_KEY=password
      - AWS_REGION=us-east-1
      - CATALOG_WAREHOUSE=s3://warehouse/
      - CATALOG_IO__IMPL=org.apache.iceberg.aws.s3.S3FileIO
      - CATALOG_S3_ENDPOINT=http://minio:9000
      - CATALOG_S3_PATH_STYLE__ACCESS=true
  minio:
    image: docker.arvancloud.ir/minio/minio
    container_name: minio
    environment:
      - MINIO_ROOT_USER=admin
      - MINIO_ROOT_PASSWORD=password
      - MINIO_DOMAIN=minio
    networks:
      iceberg_net:
        aliases:
          - warehouse.minio
    ports:
      - 9001:9001
      - 9000:9000
    command: ["server", "/data", "--console-address", ":9001"]
  mc:
    depends_on:
      - minio
    image: docker.arvancloud.ir/minio/mc
    container_name: mc
    networks:
      iceberg_net:
    environment:
      - AWS_ACCESS_KEY_ID=admin
      - AWS_SECRET_ACCESS_KEY=password
      - AWS_REGION=us-east-1
    entrypoint: |
      /bin/sh -c "
      until (/usr/bin/mc alias set minio http://minio:9000 admin password) do echo '...waiting...' && sleep 1; done;
      /usr/bin/mc rm -r --force minio/warehouse;
      /usr/bin/mc mb minio/warehouse;
      /usr/bin/mc policy set public minio/warehouse;

      #AutoMQ bucket
      /usr/bin/mc rm -r --force minio/automq-data;
      /usr/bin/mc mb minio/automq-data;
      /usr/bin/mc policy set public minio/automq-data;

      /usr/bin/mc rm -r --force minio/automq-ops;
      /usr/bin/mc mb minio/automq-ops;
      /usr/bin/mc policy set public minio/automq-ops;

      tail -f /dev/null
      "
  automq:
    container_name: "automq"
    image: docker.arvancloud.ir/automqinc/automq:1.6.0
    stop_grace_period: 1m
    environment:
      <<: *common-env
    ports:
      - "9092:9092"
      - "9093:9093"
    networks:
      - iceberg_net
    command:
      - bash
      - -c
      - |
        /opt/automq/kafka/bin/kafka-server-start.sh \
        /opt/automq/kafka/config/kraft/server.properties \
        --override cluster.id=$$CLUSTER_ID \
        --override node.id=0 \
        --override controller.quorum.voters=0@automq:9093 \
        --override controller.quorum.bootstrap.servers=automq:9093 \
        --override listeners=PLAINTEXT://:9092,CONTROLLER://:9093 \
        --override advertised.listeners=PLAINTEXT://automq:9092 \
        --override s3.data.buckets='0@s3://automq-data?region=us-east-1&endpoint=http://minio:9000&pathStyle=true' \
        --override s3.ops.buckets='1@s3://automq-ops?region=us-east-1&endpoint=http://minio:9000&pathStyle=true' \
        --override s3.wal.path='0@s3://automq-data?region=us-east-1&endpoint=http://minio:9000&pathStyle=true' \
        --override s3.wal.upload.threshold=100000 \
        --override automq.table.topic.enable=true \
        --override automq.table.topic.namespace=default \
        --override automq.table.topic.convert.value.type=by_schema_id \
        --override automq.table.topic.convert.key.type=raw \
        --override automq.table.topic.transform.value.type=flatten \
        --override automq.table.topic.errors.tolerance=invalid_data \
        --override automq.table.topic.commit.interval.ms=60000 \
        --override automq.table.topic.schema.registry.url=http://schema-registry:8081 \
        --override automq.table.topic.catalog.type=rest \
        --override automq.table.topic.catalog.uri=http://rest:8181 \
        --override automq.table.topic.catalog.warehouse=s3://warehouse/wh
    depends_on:
      - minio
      - mc
      - rest
    healthcheck:
      test: ["CMD-SHELL", "/opt/automq/kafka/bin/kafka-broker-api-versions.sh --bootstrap-server localhost:9092"]
      interval: 20s
      timeout: 20s
      retries: 5
      start_period: 20s
  schema-registry:
    image: docker.arvancloud.ir/confluentinc/cp-schema-registry:latest
    container_name: schema-registry
    depends_on:
      automq:
        condition: service_healthy
    networks:
      - iceberg_net
    ports:
      - "8081:8081"
    restart: on-failure
    environment:
      SCHEMA_REGISTRY_HOST_NAME: schema-registry
      SCHEMA_REGISTRY_KAFKASTORE_BOOTSTRAP_SERVERS: 'automq:9092'
      SCHEMA_REGISTRY_LISTENERS: http://0.0.0.0:8081
  kafka-ui:
    image: docker.arvancloud.ir/kafbat/kafka-ui:latest
    container_name: kafka-ui
    ports:
      - "9300:8080"
    environment:
      KAFKA_CLUSTERS_0_NAME: "automq-cluster"
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: automq:9092 
      KAFKA_CLUSTERS_0_SCHEMAREGISTRY_URL: http://schema-registry:8081
      KAFKA_CLUSTERS_0_PROPERTIS_REQUEST_TIMEOUT_MS: 30000
      KAFKA_CLUSTERS_0_PROPERTIS_DEFAULT_API_TIMEQUT_MS: 30000
      DYNAMIC_CONFIG_ENABLED: 'true'
    networks:
      - iceberg_net
    depends_on:
      automq:
        condition: service_healthy
    restart: unless-stopped
  trino:
    image: docker.arvancloud.ir/trinodb/trino:latest
    container_name: trino
    ports:
      - "8082:8080"
    volumes:
      - ./trino-config/catalog/iceberg.properties:/etc/trino/catalog/iceberg.properties:ro
    networks:
      - iceberg_net
    depends_on:
      - minio
      - automq
    restart: unless-stopped
  jupyter:
    image: docker.arvancloud.ir/jupyter/minimal-notebook:latest
    container_name: jupyter-duckdb
    ports:
      - "9090:8888"
    volumes:
      - ./notebooks:/home/jovyan/work
    networks:
      - iceberg_net
    depends_on:
      - minio
      - automq
    environment:
      - JUPYTER_ENABLE_LAB=yes
      - GRANT_SUDO=yes
    command: >
      bash -c "
      pip install --quiet duckdb trino &&
      start-notebook.sh --NotebookApp.token="" --NotebookApp.password=""
      "
    restart: unless-stopped




networks:
  iceberg_net:
volumes:
  minio:
    driver: local
